FROM fedora:22
MAINTAINER Nathan Sparks <nsparks@jlab.org>
RUN dnf upgrade -y && dnf install -y git make gcc gcc-c++ \
    binutils clang libX11-devel libXpm-devel libXft-devel libXext-devel \
    subversion scons cmake gcc-gfortran imake patch expat-devel blas-devel \
    lapack-devel openmotif-devel tcsh tar file emacs sqlite-devel mysql-devel \
    fftw-devel bzip2-devel python-devel blas-static lapack-static findutils \
    bzip2 && dnf clean all \
    && ln -s /usr/lib64/liblapack.a /usr/lib64/liblapack3.a \
    && ln -s /usr/include/freetype2/freetype /usr/include/freetype
CMD cd /home && /bin/bash
