# docker build -t quay.io/nathansparks/sim-recon-deps:centos7 -f Dockerfile-deps .
FROM hdbase:centos7
MAINTAINER Nathan Sparks <nsparks@jlab.org>
RUN git clone https://github.com/JeffersonLab/hdpm
WORKDIR /home/work/hdpm
#ADD settings settings
RUN /bin/bash -c "source setup.sh && julia src/hdpm.jl build cernlib evio jana"
