FROM hdbase:u14
MAINTAINER Nathan Sparks <nsparks@jlab.org>
RUN mkdir -p /home/hdpm && groupadd -r hdpm -g 573 && useradd -u 1000 \
    -r -g hdpm -d /home/hdpm -s /sbin/nologin -c "Docker image user" hdpm \
    && git clone https://github.com/JeffersonLab/hdpm /home/hdpm \
    && mkdir -p /home/hdpm/docker/data \
    && chown -R hdpm:hdpm /home/hdpm
USER hdpm
WORKDIR /home/hdpm
ENV CC=/usr/bin/clang-3.5 CXX=/usr/bin/clang++-3.5
RUN /bin/bash -c "source setup.sh && julia src/hdpm.jl build cernlib amptools evio jana"
CMD /bin/bash
