FROM centos:6
RUN yum update -y && yum install -y centos-release-SCL epel-release centos-release-scl-rh \
			&& yum install -y \
			binutils \
			blas-devel \
			boost-devel \
			bzip2 \
			bzip2-devel \
			cmake3 \
			devtoolset-3-toolchain \
			expat-devel \
			fftw-devel \
			file \
			gcc \
			gcc-c++ \
			gcc-gfortran \
			git \
			imake \
			lapack-devel \
			libX11-devel \
			libXext-devel \
			libXft-devel \
			libXi-devel \
			libXmu-devel \
			libXpm-devel \
			lsof \
			make \
			mesa-libGLU-devel \
			mysql-devel \
			openmotif-devel \
			patch \
			python27 \
			scons \
			sqlite-devel \
			subversion \
			tar \
			tcsh \
			xerces-c-devel \
			&& yum clean all \
			&& ln -s liblapack.a /usr/lib64/liblapack3.a \
			&& ln -s cmake3 /usr/bin/cmake \
			&& ln -s /opt/rh/python27/root/usr/lib64/libpython2.7.so /usr/lib64/libpython2.7.so

# Keep record of Dockerfile(s)
ADD . /docker

RUN mkdir /builds
WORKDIR /builds
COPY dot_tcshrc /root/.tcshrc

CMD cd /home && scl enable devtoolset-3 tcsh
