FROM centos:6
MAINTAINER Nathan Sparks <nsparks@jlab.org>
RUN yum update -y && yum install -y centos-release-SCL epel-release centos-release-scl-rh \
            && yum install -y python27 git make gcc-c++ gcc binutils boost-devel \
            libX11-devel libXpm-devel libXft-devel libXext-devel mesa-libGLU-devel \
            gcc-gfortran imake patch expat-devel libXi-devel libXmu-devel \
            blas-devel lapack-devel openmotif-devel tcsh tar file clang cmake3 scons \
            mysql-devel sqlite-devel fftw-devel bzip2 bzip2-devel devtoolset-3-toolchain \
            && yum clean all \
            && ln -s liblapack.a /usr/lib64/liblapack3.a \
            && ln -s cmake3 /usr/bin/cmake
CMD cd /home && /bin/bash
