# docker build -t quay.io/nathansparks/sim-recon-deps:centos6 -f Dockerfile-deps .
FROM hdbase:centos6
MAINTAINER Nathan Sparks <nsparks@jlab.org>
RUN git clone https://github.com/JeffersonLab/hdpm
WORKDIR /home/work/hdpm
#ADD settings settings
RUN scl enable python27 "source setup.sh && julia src/hdpm.jl build cernlib evio jana"
